// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sabemi.Pagamentos.Infrastructure.Persistence;

#nullable disable

namespace Sabemi.Pagamentos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908201351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sabemi.Pagamentos.Domain.Contratos.StatusContrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdContrato")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuantidadeEstornos")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadePagamentos")
                        .HasColumnType("int");

                    b.Property<string>("UltimaTransacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UltimoPagamentoUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UltimoStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotalEstornado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdContrato")
                        .IsUnique()
                        .HasDatabaseName("UX_StatusContratos_IdContrato");

                    b.ToTable("StatusContratos", (string)null);
                });

            modelBuilder.Entity("Sabemi.Pagamentos.Domain.Eventos.EventoWebhook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DuracaoProcessamentoMs")
                        .HasColumnType("bigint");

                    b.Property<string>("IdContrato")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdTransacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotivoFalha")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OrigemParceiro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PayloadBruto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecebidoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StatusPagamento")
                        .HasColumnType("int");

                    b.Property<int>("Tentativas")
                        .HasColumnType("int");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdContrato")
                        .HasDatabaseName("IX_EventosWebhook_IdContrato");

                    b.HasIndex("IdTransacao")
                        .IsUnique()
                        .HasDatabaseName("UX_EventosWebhook_IdTransacao");

                    b.HasIndex("RecebidoEmUtc")
                        .HasDatabaseName("IX_EventosWebhook_RecebidoEmUtc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_EventosWebhook_Status");

                    b.ToTable("EventosWebhook", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
